name: gadgetid_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  flutter:
    sdk: flutter
  get: 4.6.1
  get_storage: ^2.0.3
  introduction_screen: ^2.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
